{% set name = "geojson" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58a7fa40727ea058efc28b0e9ff0099eadf6d0965e04690830208d3ef571adac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37 or py>312]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - geojson
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv tests
  

about:
  home: https://github.com/jazzband/geojson
  summary: 'Python bindings and utilities for GeoJSON'
  description: |
    This Python library contains, functions for encoding and 
    decoding GeoJSON formatted data. Classes for all GeoJSON Objects.
    An implementation of the Python __geo_interface__ Specification
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  dev_url: https://github.com/jazzband/geojson
  doc_url: https://github.com/jazzband/geojson/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
