{% set version = "2.4.1" %}

package:
  name: geojson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geojson/geojson-{{ version }}.tar.gz
  sha256: b175e00a76d923d6e7409de0784c147adcdd6e04b311b1d405895a4db3612c9d

build:
  number: 0
  noarch: python 
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geojson

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: 'Python bindings and utilities for GeoJSON'

extra:
  recipe-maintainers:
    - ocefpaf
