{% set version = "3.1.0" %}

package:
  name: geojson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geojson/geojson-{{ version }}.tar.gz
  sha256: 58a7fa40727ea058efc28b0e9ff0099eadf6d0965e04690830208d3ef571adac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<37]

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - geojson
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv tests
  

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: 'Python bindings and utilities for GeoJSON'

extra:
  recipe-maintainers:
    - ocefpaf
