{% set version = "2.5.0" %}

package:
  name: geojson
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geojson/geojson-{{ version }}.tar.gz
  sha256: 6e4bb7ace4226a45d9c8c8b1348b3fc43540658359f93c3f7e03efa9f15f658a

build:
  number: 0
  noarch: python 
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geojson

about:
  home: https://github.com/frewsxcv/python-geojson
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: 'Python bindings and utilities for GeoJSON'

extra:
  recipe-maintainers:
    - ocefpaf
