travis:
  secure:
    BINSTAR_TOKEN: yVT4WOgHYg8NtyY4sLyZZB0S6e5LSA9AMmxHAg1KYZxDdutu4CGQRSdCLpvVcCS+E6TL2SZNNqtKfZ2+t9GM5WFArLEOQn6BqV0inNmKGhCYqsFRrheAmMTAdkbCcei8wfyH5G8gg3bRxjWeVtm0wGAZ5/+ooKBOCLoai1RpHZE6zEY+yJ6QB+Q5Agcd+K+ZxzX3dNGSq6C+UZk8aUBntSO0KgGjutl6VF1CHKLPUP15L0p8In4lLiZQj8Z9BUVyUGSSvg5owd+WfxcxyrKi09KT1P1UbbM2g8mPSHiW4HWPF/irXa4OwDki3Q5sf9jx4GPEwuBFSUILVgPIT1YoBvExN+K5lfGQ9QzSvj+6cjliaj3liuK2UEQ+xNnR09mKXbc1/X4cjq/cUQVe6c5fSuozQG09zC1KfLga4UjLU51k9EhzPeqH8cZ+O7WEwSkLEkTmjhf7FXwc2xe14rsIbTDuNbBR0fPX+mh3FERLk0ajMJ20PNAb46r6x1ZYhLikHw6+XSSgwZ97LUPjiMUsPBg3R1/arrkEaSalyZJTBPB3tkZ50AARKPFSqYoaZHtWeaT2YXWXpQlySXiao2T6g+CMBEI3dHoPqjoUDujpyBG2r0jLjpv89Ck3lTLEQhZMZNOALNmSkb8hhkGvaihwaF2nVaznD5fAaTDBVmTT+Qs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
