travis:
  secure:
    BINSTAR_TOKEN: SGJIGbsODUYz14zvOOz8alex+piESctEPzgW8T0iRT5/UlAsJfavOSHXfbouCLFwNF1CylYTo8f2ugc+udXvGYilOB88t6FRWcSi276dcanJ4SLt1oUa8ddL9nALGEKCpWLUFy8FfRc35epsfTjXFjIlk02MreQvDhnMYJ2gXBBjttZRKLDk3LlKw2fK6nK1AJNmS12WR5amKzVgAedS6OhQRJ8WuQQuj9VLN9mtc4UqW2Up1M0dak26aBptzAvGcUtG/lDS28FZezmCIx7hggzSicVVOx00K4119MEU/PZx7loqyuOeRzai+hebX66++bGmyluFM403YAd73iFbLRaU0ZOHpf/xMb22T7Uvt56IY3lDv0kWjNtWK+PsCGLlVgswO/kTnU5LNvwGHLyThb3Ngfdl53NUQelsNytp3T32xsism8zNh9k/wdnPg+HwFBWWKu+4hSx6lqWsKGZ/WRR1HH+T+YxZCDGn8ixlkHtVmhniiIjWFEDxL8Z4twYQGh9HkyPO0MUppnJea8G02Zz8OkN3ZDs7yFV6oz1BWzxqWsibTXlMPf9gg8dak/9dQRLKiLsVPJ+brO98yuBLIetA8eC+Q/nmVZ06xJVNF/j50cNSCuwUmMQWXftJ6zLxllWCwS6kaBGjSIkKb7FwRw8Cm8wE634Ign+Y5zzPbSo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
