travis:
  secure:
    BINSTAR_TOKEN: NnsJgauWLjMKHpQLj7Zzh/6HO6GV2ALVOTQkrlAaI0Xw5mTD5T5J0CnS1pF6hggoGunUtOvVp6X1ARuS2O1DJAZef/HwK2iJn6S8NhHCbYivLazv/KFhINNO9LL9AN9iaGvKtLC/FIEOKPqmrkX5hQMQE0yhYht4EO1cV1aQcbZn8HXh83MunQuBdWZ98KMb9AzeJnxlni6ETXghp2n0gVQ5WnqOl9CICkNi/7fT0vtJK6SUrszY61Xo1UdwH3e2KjpNIjY+8yVRKk1cLJzR9YJVWdzG0Fh8mmdNKYespftTCzwW2SPsqwTG2v9pj980X3Ljd7GARELxNUIQG14nuTFqTRpzGpKVBPXw/CzHOy1RD+snrbyJzuaufdNRNb8U8ZuCWzX/AMmmFOhuQoHn2gUBzB9BdfOAXPxsNKkcldmpqDx7IZTHaNIPy62f4r29zqtltvMyKINkthFPA2bnpGd/yyuuUuBuocWGSwp4pVTR5/FOrOlAN0MVUGfJp295X+Emp/1WcrN8R4Ui7+Rm5iBFYOAJMuUUdj9r7vqdCd2Chudiw8Qc7RePKM6aB2m+7Lp7WxiYYmaaKCFqzX+M8x2TohFzOTWiIW1fHNBlD77frPlvtF2VgV4a8ym9Y9PcRDxqSmZ2+dqH/Nlm+40HhYmvW5PrxonfHN+kJifAjWY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
