travis:
  secure:
    BINSTAR_TOKEN: JVdPWlR0YzPnffz7lxI9MSS0kl/rFOUs6MafiOk58+p7JLVhbeDdAgXBRPMEtsqHZLuBkuhhyH2rG2g/kHHgTZYJgnsQ6hfyAp8VRc4eHXrQFgz6Qsv9Ik3hNocPe+XGT3ZlleuX4O2sgnzwkPdRzSwOhrLtGctY+r0iiQFS0B7QDHa6MQUSrkMeJ/7z5BbMtsvViMjfmXgIAu0wfx5cvIG9QtRvl/xkQsMQLnkITbo1FxAamXMZe0nQOCum7w8F6E+q6/i7TUXnZ0Id2ePtjqJhLcDyEFUXhLjYETbMommvpRSrh6lKi1+1Zb+cNQaCvGtIllCbUtUYPZa9g0c/+xQ8ijRCBjUrR0iqpcv5ckclVVUIEc3ebzeAzyhQR870ZeAnEcOVnWoGwxeDzNd87FpDifs5hNO5WejbQGPwkJv95NOKXE4PINWrjb3hytQE6O1HKBkpyd2ltG8YhJx64bNiKMh5kDIDSzM2sc0UOvzuxq5fJKL+r4gxMuBbra7lSFk7g+eWlLjLf5QSjfowZMiysytaTmr/AgDyIzNCt/FBwn7APuNSTAa26CU1htPbhei/PnRy469BoAU06R4HDsxjklJ3qUbKCKwhjwG7e5c1Tm8ppSWlgZp4k9MUEumrNBlOBCntIw7edMTZiEXjCuqO8NAbV683384FZT9VG7M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
